import { Member } from '@/types';

const raw = [
  { name: 'lok', gender: 'male' },
  { name: 'taiyo', gender: 'male' },
  { name: 'takase', gender: 'male' },
  { name: 'yun', gender: 'female' },
  { name: 'mami', gender: 'female' },
  { name: 'rinko', gender: 'female' },
  { name: 'tomone', gender: 'female' },
  { name: 'motoyasu', gender: 'male' },
  { name: 'takehiro', gender: 'male' },
  { name: 'atuhiro', gender: 'male' },
  { name: 'sara', gender: 'female' },
  { name: 'tomoki', gender: 'male' },
  { name: 'rei', gender: 'female' },
  { name: 'yuri', gender: 'male' },
  { name: 'atushi', gender: 'male' },
  { name: 'manaka', gender: 'female' },
  { name: 'nao', gender: 'female' },
  { name: 'taiga', gender: 'male' },
  { name: 'jeon', gender: 'male' },
  { name: 'hirari', gender: 'female' },
  { name: 'so', gender: 'male' },
  { name: 'riku', gender: 'male' },
  { name: 'luna', gender: 'female' },
  { name: 'matsuken', gender: 'male' },
  { name: 'yuki', gender: 'male' },
  { name: 'tokko', gender: 'female' },
  { name: 'kyotaro', gender: 'male' },
  { name: 'uoya', gender: 'male' },
  { name: 'oono', gender: 'male' },
  { name: 'an', gender: 'female' },
  { name: 'takako', gender: 'female' },
  { name: 'tomoya', gender: 'male' },
  { name: 'keina', gender: 'female' },
  { name: 'yuto', gender: 'male' },
  { name: 'tessho', gender: 'male' },
  { name: 'naoya', gender: 'male' },
] as const;

export const DEFAULT_MEMBERS: Member[] = raw.map((m, i) => ({
  id: `m-${i + 1}`,
  name: m.name,
  gender: m.gender,
  isAbsent: false,
}));
